### ISSUE TITLE
[BUG] Some False / true function arguments are surrounded by quotes?

### ISSUE THREAD

**Issue by fvet** [waldo1001/crs-al-language-extension#144]
Having formatted al my *.al files (5200+) I get a lot of compilation errors because of surrounding quotes are added on true / false arguments on function calls. Tried to disable the FormatOnSave, without luck. Had to uninstall the CRS extension ...

Previous function call before format
   ```
ShowSourceDocOrTransaction(false); 
CheckTransaction(true);
   ```

New function call after format
   ```
ShowSourceDocOrTransaction("false"); // Double quotes ??? 
CheckTransaction("true"); // Double quotes ??? 
   ```

Function definition

   ```
 local procedure ShowSourceDocOrTransaction(pbolShowSourceDocument: Boolean)
    var
        lrecRegisteredTrans: Record "NVT WMS Registered Transaction";
        liCounter: Integer;
        liTypes: Integer;
        liPossibleTypes: array[10] of Integer;
    begin
...
```

Hint? Function name seem to have 'transaction' in their name...

**Comment by waldo1001** [comment]
the problem here is that you comply with the regex for "action(true)", which needs to be set to "action('true')".

**Comment by waldo1001** [comment]
Quick fix would be to rename your function (with F2, you can rename all functioncalls in one go) so that it would not end with "action".  Or move you code out of the page ... don't know if that's possible.

I tried to quickly chang the regex, but it's breaking many tests - so I'm not going to try to quickly fix this .. .

Hope this works for now.. .

**Comment by fvet** [comment]
Changing the function name will do fine for these cases. No need to updated the regex.
Thanks to pointing me in the right direction!
