### ISSUE TITLE
No Difference in FileNamePattern 

### ISSUE THREAD

**Issue by MLadewig78** [waldo1001/crs-al-language-extension#147]
I use the Patterns to Prefixe and Change Filename
"CRS.FileNamePattern": <ObjectNameShort>.<ObjectName>.al
"CRS.ObjectNamePrefix" : "My_"

On File "Remaming" the Prefix Appears to the Object Name and also to the Filename.
When i use the Pattern "CRS.FileNamePattern": "<Prefix><ObjectNameShort>.<ObjectName>.al"
In the Filename are two Prefix entries.
is there an Propertie  to change this behavior or is it a Bug?

Here are some screenshots
![Issue1](https://user-images.githubusercontent.com/54710141/69341173-59728c00-0c69-11ea-8625-2d4afa794a20.png)
![Issue2](https://user-images.githubusercontent.com/54710141/69341175-59728c00-0c69-11ea-9b5e-b32203163545.png)

**Comment by waldo1001** [comment]
the "objectnameprefix" is going to put a prefix in the object name.
the "<prefix>" in the pattern, is going to put it in the filename.

thing is, when the object name is already prefixed, then you'll have the prefix as well in the "objectnameshort" .. .

You could see it as a bug, indeed.  But I don't want to change behaviour too much since lots of projects and people have been using it already as is.

There is an "RemovePrefixFromFilename" property you can set as well - did you try that out?

**Comment by MLadewig78** [comment]
Yeah this works
thx

![Hit](https://user-images.githubusercontent.com/54710141/69800020-b4116800-11d4-11ea-84ad-707a6eeddf9b.png)
