### ISSUE TITLE
Remove the '.' in assistedsetup snippets

### ISSUE THREAD

**Issue by SirBETE** [waldo1001/crs-al-language-extension#162]
Because there's a '.' in the assistedsetup snippet (pre & post 15.0 versions), each time you type a '.' those 2 snippets are suggested. 
if you then accidentally use enter or tab, a snippet is inserted, which is annoying.

Could it be possible to remove this '.'?

![image](https://user-images.githubusercontent.com/34303738/79208024-cf0e0d00-7e41-11ea-8854-c7ca4c2e3c4e.png)

**Comment by waldo1001** [comment]
Will do!  Thanks for pointing out!

Sent from my iPhone

On 14 Apr 2020, at 11:22, SirBETE <notifications@github.com> wrote:

﻿

Because there's a '.' in the assistedsetup snippet (pre & post 15.0 versions), each time you type a '.' those 2 snippets are suggested.
if you then accidentally use enter or tab, a snippet is inserted, which is annoying.

Could it be possible to remove this '.'?

[image]<https://user-images.githubusercontent.com/34303738/79208024-cf0e0d00-7e41-11ea-8854-c7ca4c2e3c4e.png>
