### ISSUE TITLE
Disregard comments

### ISSUE THREAD

**Issue by waldo1001** [waldo1001/crs-al-language-extension#167]
![image](https://user-images.githubusercontent.com/12088142/80411003-c1d63100-88cb-11ea-9e24-74abf26dfd12.png)

**Comment by dtkb** [comment]
It would be great if this could be sorted. If I'm forced by some non-extensible third party to copy and 'override' one of their objects, I like to have the original ID/name as a comment above our ID/name. But I can't do that with CRS Auto Rename because it uses the commented details and renames using those, not the ID/name that actually get compiled...

So, this codeunit:
![image](https://user-images.githubusercontent.com/63455896/106765929-3e532880-6631-11eb-9609-7ef3200d2398.png)

gets Auto-Renamed to have the wrong, original, commented-out ID and name:
![image](https://user-images.githubusercontent.com/63455896/106765959-47dc9080-6631-11eb-9767-98c4786d1d6d.png)

**Comment by waldo1001** [comment]
Fix should have been implemented in v1.4.1
