### ISSUE TITLE
Prefix or Suffix - With "Rename Symbol"

### ISSUE THREAD

**Issue by josnelissen** [waldo1001/crs-al-language-extension#19]
Very useful extension.
A snippet to add a prefined prefix or suffix to object names would be helpful

**Comment by waldo1001** [comment]
Very nice idea!  Will do!

**Comment by waldo1001** [comment]
@josnelissen 
Done - hope you like it :-)

**Comment by josnelissen** [comment]
Suffix/prefix are being added but existing references are not updated. So using it on a objects already referenced to you have to do some updating.
If you can fix it, that would be great.

**Comment by waldo1001** [comment]
Just for my reference:
https://stackoverflow.com/questions/46839773/vscode-extension-rename-symbols

**Comment by Tristanas** [comment]
Is this feature still in the plans?
It would highly improve the efficiency of certain tasks, like adding prefixes after an upgrade to extensions. Currently, if I add prefixes with the "Rename all files" function I get 170 errors in a small test project due to all of the lost references.

**Comment by navdotnetreqs** [comment]
We need to update a lot of old code to include company suffixes for objects and fields. Frankly it's very painful to go through every object and select "rename symbol" manually for them all, but it's still faster than using this extension to rename the objects and break all references, and then go through all the references one by one.

So why couldn't this extension use the rename symbol -functionality when adding suffixes to objects and or/fields?

**Comment by waldo1001** [comment]
Simply because I'm not capable.. sorry.  I'm not a typescript developer, and this requires quite some tricks, including NOT using regex, which I am.  I had many go's at it, and I simply failed - it took me days of work to get nowhere... all that for a "feature" that isn't even repeatable: it's intended to only be used once.

I AM accepting pull requests, so please have a go at it.  

Tip: 
VSCode has quite some smart find/replace functions, including regex and such.
