### ISSUE TITLE
Rename/Reorganize feature: Update all references if affixes are added to fields

### ISSUE THREAD

**Issue by ngiessel** [waldo1001/crs-al-language-extension#208]
When renaming a file and the corresponding object (adding mandatory affixes), all references to this object are properly updated.

Fields also have the affix added, however, contrary to my expectations, references to the fields are not updated, causing errors.

This means you would have to
- manually use the Rename Symbol feature on all fields before reorganizing your files
- or fix all references manually after reorganizing the files.

Is this something that could be changed?

**Comment by waldo1001** [comment]
I know, the references are not updated.  Simply because this is way over my head: I never tap into the symbol, stuff.  

I spent a lot of time trying to make this work, but decided to give up.  Also because this isn't a function that is continuously used, it's only used once to get going.  

Sorry ... :(

**Comment by waldo1001** [comment]
I have done this for a number of cases, and there are actually quite some ways to efficiently Find/Replace in VSCode.. .

**Comment by ngiessel** [comment]
I understand, thanks anyway!
